### ISSUE TITLE
Chart doesn't grow

### ISSUE THREAD

**Issue by rigon** [chrisant996/elucidisk#4]
The chart adapts its size according with window size. However it stops growing at a certain point. If you have a big screen (in my case a 4K monitor), I can't use all screen size for the chart.

I don't know if this behavior was intended, but I believe it is useful remove this restriction.

Here is screenshot to illustrate the issue:
![Chart doesn't grow](https://github.com/chrisant996/elucidisk/assets/1102280/0bb3d37a-c91c-4c94-8cee-d604f348693e)

**Comment by chrisant996** [comment]
@rigon what DPI is your monitor?

(4K is resolution -- I'm interested in the DPI scaling factor, e.g. 100%, 150%, 200%, 225%, etc.)

**Comment by rigon** [comment]
So, my screen is 4K (3840x2160), 32 inches.
The current scaling factor that I have set on Windows is 175%.

**Comment by chrisant996** [comment]
It looks like you want an option that applies a scale factor to the chart to make it as large as possible within the window (perhaps up to some maximum scale factor).

I experimented quite a bit with that, but I found it to be very disorienting, because then the size depends on the number of subdirectories.  Each click on anything dramatically changed the scale, and also the chart would always start out huge and then "snap" to smaller sizes progressively whenever a new "deepest subdirectory" is found.  It didn't work well in practice.

The size of the chart scales based on window dimensions, but also based on a minimum ring thickness and fitting a certain "maximum depth" of subdirectories -- even if the current chart's depth doesn't actually reach that depth, because otherwise the size changes with every click (and also changes repeatedly while scanning a drive), which I found to be highly disorienting.

Your window is max height, so the program allows fitting a maximum depth subdirectories (which is also affected by the "Show Proportional Area" option in the context menu).  But your drive has very few directories, so the chart isn't "deep", so there's empty space around it.

I can do some more experimentation to try to come up with something that allows a little more magnification, without becoming disorientating due to variability of size.  Maybe I can offer an option to control the "maximum depth" that the chart scales to.

Here's an example of a chart that is at max depth, as a maximized window.  Its radius extends as far as possible without overlapping anything else, and while still being a circle (vs an ellipse).

![image](https://github.com/chrisant996/elucidisk/assets/17440311/179f3cf7-2e88-4a52-a461-55c275c8deb3)

And here's the same chart, with the window size reduced to the minimum height.

![image](https://github.com/chrisant996/elucidisk/assets/17440311/7a7dd2f1-0057-46da-a3d6-8ab8ebf48bd5)

**Comment by chrisant996** [comment]
In other words, it's working as intended, but that specific drive has only a "shallow" depth of subdirectories, so there's empty space around the outside.

Would you like an option to control the maximum number of subdirectories "deep" to show in the chart, which would control the maximum scale factor of the chart?  E.g. setting it to 3 would make the chart quite large, at the expense of not showing as much detail (the tiny gray bars around the outside edge indicate when there's "deeper" stuff that can't be shown in the chart -- they're both hover-able for tooltips, and also clickable for opening or etc).

**Comment by rigon** [comment]
I see what you mean, actually is working as intended! Now that I given some though to it, is more complex than I expected (typical newbie) and you have already have spent a good amount of effort on it.

What made me think that wasn't resizing properly was due to the fact that I didn't realize that it was changing the number of layers dynamically, even if the number of sub-directories isn't deep enough. I must agree with you, it should be very confusing if the size of the layers would change whilst navigating. I think is working perfectly indeed.

Regarding the option to control the number of layers, would be nice to have but I don't believe that is that critical.
The reason of raising this issue was because I find useful showing as much folders names as possible, it helps me navigating more easily. And the bigger the chart, the better chance of showing the name. The option you are proposing does just that.

**Comment by chrisant996** [comment]
@rigon I think the chart was slightly smaller than intended when using less than 200% scaling on a 4K monitor.  v1.2 should fix it to be the intended size.

Regarding the motivation for wanting a larger chart, I think a better approach could be to allow folder names to wrap to a second line, and/or truncate them with an ellipsis if they don't fit.  I've opened #5 to track that.
